FROM resin/%%RESIN_MACHINE_NAME%%-python:2.7

WORKDIR /usr/src/app
ENV INITSYSTEM on

ENV MIRAIPOTVERSION 8f5ae373eecaa14f7323860aeb464d313ee4eb7e
RUN git clone https://github.com/CymmetriaResearch/MTPot.git && \
    cd MTPot && \
    git checkout -b build ${MIRAIPOTVERSION} && \
    pip install -r requirements.txt

CMD python MTPot/MTPot.py -o /data/MTPot.log MTPot/mirai_conf.json
